project:
  type: website
  output-dir: docs

website:
  title: "DSCI 140 Web Tutorials"
  navbar:
    left:
      - Factor Tutorial.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    