project:
  type: website
  output-dir: docs

website:
  title: "DSCI 140 Web Tutorials"
  navbar:
    left:
      - intro_R_tutorial_penguin.qmd
      - string_tutorial_penguin.qmd
      - missing_data_tutorial_penguin.qmd
      - factor_tutorial.qmd
      - reshape_tutorial.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    